### ISSUE TITLE
[14.0] [mail_tracking] New user on e-commerce email

### ISSUE THREAD

**Issue by baba75** [OCA/social#1145]
When a new user inserts his address details on the eCommerce and mail_tracking is installed, an Internal Server Error is thrown back.

## Module
mail_tracking

## Describe the bug
500 - Internal Server Error

## To Reproduce
Odoo 14: (tested on Runboat)

1. install mail_tracking, eCommerce and set "Free sign up" on permission settings
2. log out, and buy something in the shop
3. in address management, choose to log in and then "Don't have an account?"
4. insert your data and save

**Expected behavior**
Normal checkout process should continue

**Additional context**
Traceback (most recent call last):
  File "/opt/odoo/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/opt/odoo/odoo/http.py", line 813, in dispatch
    r = self._call_function(**self.params)
  File "/opt/odoo/odoo/http.py", line 370, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo/http.py", line 358, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo/http.py", line 919, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo/http.py", line 544, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/addons/website_sale/controllers/main.py", line 739, in address
    partner_id = self._checkout_form_save(mode, post, kw)
  File "/opt/odoo/addons/website_sale/controllers/main.py", line 638, in _checkout_form_save
    Partner.browse(partner_id).sudo().write(checkout)
  File "/mnt/data/odoo-addons-dir/mass_mailing_list_dynamic/models/res_partner.py", line 12, in write
    return super(ResPartner, self.with_context(syncing=True)).write(vals)
  File "/mnt/data/odoo-addons-dir/mass_mailing_partner/models/res_partner.py", line 74, in write
    res = super().write(vals)
  File "/opt/odoo/addons/snailmail/models/res_partner.py", line 26, in write
    return super(ResPartner, self).write(vals)
  File "/opt/odoo/addons/partner_autocomplete/models/res_partner.py", line 199, in write
    res = super(ResPartner, self).write(values)
  File "/mnt/data/odoo-addons-dir/mail_tracking_mailgun/models/res_partner.py", line 193, in write
    return super().write(vals)
  File "/opt/odoo/odoo/addons/base/models/res_partner.py", line 556, in write
    result = result and super(Partner, self).write(vals)
  File "/opt/odoo/addons/mail/models/mail_activity.py", line 788, in write
    return super(MailActivityMixin, self).write(vals)
  File "/mnt/data/odoo-addons-dir/mail_tracking/models/mail_bounced_mixin.py", line 35, in write
    vals["email_bounced"] = mte_obj.email_is_bounced(email)
  File "/mnt/data/odoo-addons-dir/mail_tracking/models/mail_tracking_email.py", line 228, in email_is_bounced
    res = self.sudo()._email_last_tracking_state(email)
  File "/mnt/data/odoo-addons-dir/mail_tracking/models/mail_tracking_email.py", line 242, in _email_last_tracking_state
    order="time DESC",
  File "/opt/odoo/odoo/models.py", line 4855, in search_read
    records = self.search(domain or [], offset=offset, limit=limit, order=order)
  File "/opt/odoo/odoo/models.py", line 1708, in search
    res = self._search(args, offset=offset, limit=limit, order=order, count=count)
  File "/mnt/data/odoo-addons-dir/mail_tracking/models/mail_tracking_email.py", line 194, in _search
    ids = self.browse(ids)._find_allowed_tracking_ids()
  File "/mnt/data/odoo-addons-dir/mail_tracking/models/mail_tracking_email.py", line 171, in _find_allowed_tracking_ids
    for x in msg_linked
  File "/mnt/data/odoo-addons-dir/mail_tracking/models/mail_tracking_email.py", line 174, in <listcomp>
    not any({x[1], x[2]}) and x[3] in partner_ids
IndexError: tuple index out of range

**Comment by baba75** [comment]
The issue is not happening if the 'auto_delete' flag of mail.template, (Auth Signup: Odoo Account Created in this case) is set to false.

**Comment by pedrobaeza** [comment]
Fixed in #1148

**Comment by baba75** [comment]
Thank you @pedrobaeza !
