### ISSUE TITLE
mail_tracking showing Error: Cannot find the definition of component "MessageFailedBox"

### ISSUE THREAD

**Issue by visiniaga** [OCA/social#1193]
## Module
mail_tracking

## Describe the bug
already update to the latest mail_tracking-14.0.3.1.1.zip, opening module with chatter showing error 
Traceback:
Error: Cannot find the definition of component "MessageFailedBox"
at QWeb.eval (eval at _compile (https://odoo14.visiniaga.co.id/web/content/85693-cd5ebe4/web.assets_common.js:971:178), :105:35)
at QWeb.fn (https://odoo14.visiniaga.co.id/web/content/85693-cd5ebe4/web.assets_common.js:955:173)
at QWeb.render (https://odoo14.visiniaga.co.id/web/content/85693-cd5ebe4/web.assets_common.js:962:20)
at __owl__.renderFn (https://odoo14.visiniaga.co.id/web/content/85693-cd5ebe4/web.assets_common.js:1314:113)
at Chatter.__render (https://odoo14.visiniaga.co.id/web/content/85693-cd5ebe4/web.assets_common.js:1294:33)
at Chatter.__prepareAndRender (https://odoo14.visiniaga.co.id/web/content/85693-cd5ebe4/web.assets_common.js:1292:29)

## To Reproduce
**Affected versions**:
mail_tracking-14.0.3.1.1

1. odoo14 enterprise
2. it seem have related with module sh_activities_management-14.0.40
3. opening showing error

**Expected behavior**
it should open correctly

**Additional context**
Add any other context about the problem here. (e.g. OS, Python version, ...)
odoo14e-20230303
python-3.8.8
centos8

module sh_activities_management-14.0.40 have been add feature for done activities and cancel activities on chatter
https://apps.odoo.com/apps/modules/14.0/sh_activities_management/
![image](https://github.com/OCA/social/assets/43309334/773e2546-a536-4434-aa3e-d6958686e5ff)

MessageFailedBox only show on module mail_tracking
![image](https://github.com/OCA/social/assets/43309334/c3da8ce5-760a-4818-b01c-0abd6c12391f)

**Comment by chienandalu** [comment]
I'm afraid we can't give support to interactions with non OCA modules. If you can repeat the issue in a runboat with the standard modules, we can consider the issue.
