### ISSUE TITLE
mail_debrand: with digiest mails  (got an unexpected keyword argument 'options')

### ISSUE THREAD

**Issue by jefafafah** [OCA/social#1250]
Traceback (most recent call last):
  File "/opt/odoo/odoo-server/odoo/http.py", line 1589, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/opt/odoo/odoo-server/odoo/service/model.py", line 133, in retrying
    result = func()
  File "/opt/odoo/odoo-server/odoo/http.py", line 1616, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/opt/odoo/odoo-server/odoo/http.py", line 1820, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "/opt/odoo/odoo-server/odoo/addons/base/models/ir_http.py", line 154, in _dispatch
    result = endpoint(**request.params)
  File "/opt/odoo/odoo-server/odoo/http.py", line 697, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/opt/odoo/odoo-server/addons/web/controllers/dataset.py", line 46, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/odoo-server/addons/web/controllers/dataset.py", line 33, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo-server/odoo/api.py", line 466, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/odoo-server/odoo/api.py", line 453, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/odoo-server/addons/digest/models/digest.py", line 124, in action_send_manual
    return self._action_send(update_periodicity=False)
  File "/opt/odoo/odoo-server/addons/digest/models/digest.py", line 137, in _action_send
    digest.with_context(
  File "/opt/odoo/odoo-server/addons/digest/models/digest.py", line 149, in _action_send_to_user
    rendered_body = self.env['mail.render.mixin']._render_template(
TypeError: MailRenderMixin._render_template() got an unexpected keyword argument 'options'

The above server error caused the following client error:
RPC_ERROR: Odoo Server Error
    at makeErrorFromResponse (https://xxxx.xx/web/assets/452-f9c341f/web.assets_backend.min.js:987:163)
    at XMLHttpRequest.<anonymous> (https://xxxx.xx/web/assets/452-f9c341f/web.assets_backend.min.js:995:13)

**Comment by StefanRijnhart** [comment]
You don't mention an Odoo major version, but this is fixed in https://github.com/OCA/social/pull/939 for 15, and landed in the migration in 16.0.
