### ISSUE TITLE
[16.0] OwlError: duplicate key in error message

### ISSUE THREAD

**Issue by kmagusiak** [OCA/social#1253]
## Module
mail_tracking

## Describe the bug
When opening a form which has multiple failed messages to retry, we get an error.

```
UncaughtPromiseError > OwlError
Uncaught Promise > Got duplicate key in t-foreach: undefined
OwlError: Got duplicate key in t-foreach: undefined
    at MessagingClass.template (eval at compile (https://www.edi.be/web/assets/1630502-f13e9bb/web.assets_common.min.js:2057:374), <anonymous>:249:51)
    at node.renderFn (https://www.edi.be/web/assets/1630502-f13e9bb/web.assets_common.min.js:1613:210)
    at node.renderFn (https://www.edi.be/web/assets/1630502-f13e9bb/web.assets_common.min.js:1614:207)
    at Fiber._render (https://www.edi.be/web/assets/1630502-f13e9bb/web.assets_common.min.js:1496:96)
    at Fiber.render (https://www.edi.be/web/assets/1630502-f13e9bb/web.assets_common.min.js:1495:6)
    at ComponentNode.render (https://www.edi.be/web/assets/1630502-f13e9bb/web.assets_common.min.js:1571:56)
```

What would be your expected behavior in this case?
No errors

## To Reproduce
**Affected versions**: 16.0

1. Find an object with multiple failed messages
2. Open the form view

**Expected behavior**
-

**Additional context**
-

**Comment by pedrobaeza** [comment]
@payen000 can you please check?

**Comment by payen000** [comment]
Hello @pedrobaeza,

Sorry for the delay in answering, I have my hands a little full at the moment, I can check this starting next week (hopefully a little earlier), is that ok for you?

**Comment by pedrobaeza** [comment]
Don't worry, when you are able to, and you also don't have the obligation.

**Comment by kmagusiak** [comment]
Just a note, it seems to happen only in debug mode.

**Comment by kmagusiak** [comment]
Fix was merged
