### ISSUE TITLE
[16.0] base_search_mail_content: Unable to access collaborator view in tasks within a project as portal user

### ISSUE THREAD

**Issue by Jaimermaccione** [OCA/social#1374]
### Module
base_search_mail_content
### Describe the bug
When a portal user who has been granted collaborator access to a project tries to view the tasks within that project, an error occurs, and no tasks are displayed. The error message is as follows:

```
Error: Missing field string information for the field 'message_content' from the 'project.task' model
    at http://localhost:16069/web/assets/448-676560f/project.webclient.min.js:6091:258
    at traverse (http://localhost:16069/web/assets/448-676560f/project.webclient.min.js:6086:200)
    at http://localhost:16069/web/assets/448-676560f/project.webclient.min.js:6086:242
    at Function.each (http://localhost:16069/web/assets/439-ba25088/web.assets_common.min.js:173:149)
    at traverse (http://localhost:16069/web/assets/448-676560f/project.webclient.min.js:6086:211)
    at processArch (http://localhost:16069/web/assets/448-676560f/project.webclient.min.js:6090:180)
    at generateLegacyLoadViewsResult (http://localhost:16069/web/assets/448-676560f/project.webclient.min.js:6088:106)
    at http://localhost:16069/web/assets/448-676560f/project.webclient.min.js:3172:447
```
### To Reproduce
**Affected versions:**
16.0
**Steps to reproduce the behavior:**

1. Create a project and grant access to a portal user.
2. Log in as that portal user.
3. Access the project to view the tasks within it.
4. Observe the error message.

### Expected behavior
The portal user should be able to view the tasks within the project without encountering any errors.

### Additional context

Error's screenshot:

![image](https://github.com/OCA/social/assets/153611478/08fcd532-8aaa-4ffd-bddc-5ee5f41ba369)

**Comment by yostashiro** [comment]
This is a duplicate of #1204 and has been fixed with #1205.
