### ISSUE TITLE
[8.0][mail_tracking_mass_mailing]  Error and emails not being sent

### ISSUE THREAD

**Issue by whotopia** [OCA/social#162]
I have the mail_tracking_mass_mailing and mail_tracking modules installed.   Outbound emails are not working properly.  Even if I remove the mass mailing modules, the email still doesn't work.    I get the error in my logs as follows:

`
2017-04-07 10:57:12,734 4958 ERROR xxxx-yyyy-org openerp.addons.mail.mail_mail: failed sending mail.mail 3230
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/openerp/addons/mail/mail_mail.py", line 261, in send
    email_list.append(self.send_get_email_dict(cr, uid, mail, context=context))
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/mass_mailing/models/mail_mail.py", line 100, in send_get_email_dict
    res = super(MailMail, self).send_get_email_dict(cr, uid, mail, partner, context=context)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 372, in old_api
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/.local/share/Odoo/addons/8.0/mail_tracking/models/mail_mail.py", line 40, in send_get_email_dict
    tracking_email = m_tracking.sudo().create(vals)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 266, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/.local/share/Odoo/addons/8.0/mail_tracking_mass_mailing/models/mail_tracking_email.py", line 38, in create
    self.tracking_ids_recalculate(
AttributeError: 'mail.tracking.email' object has no attribute 'tracking_ids_recalculate'
`

**Comment by pedrobaeza** [comment]
You have updated the code but haven't updated your modules in Odoo.
