### ISSUE TITLE
[10.0] Mail tracking for Mailgun

### ISSUE THREAD

**Issue by collex100** [OCA/social#234]
I installed the module Mail tracking for Mailgun. I entered the parameters:
mailgun.apikey: 
mailgun.api_url: 
mailgun.validation_key: 

When checking mail or by pressing the Re-sync Mailgun button, I receive the following message:
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 641, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 333, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 326, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 506, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/site-packages/odoo/addons/web/controllers/main.py", line 894, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/lib/python2.7/site-packages/odoo/addons/web/controllers/main.py", line 882, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python2.7/site-packages/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python2.7/site-packages/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/var/lib/odoo/addons/10.0/mail_tracking_mailgun/models/mail_tracking_email.py", line 240, in action_manual_check_mailgun
    content = json.loads(res.content, res.apparent_encoding)
  File "/usr/lib64/python2.7/json/__init__.py", line 351, in loads
    return cls(encoding=encoding, **kw).decode(s)
  File "/usr/lib64/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

```
What could this mean?
Tnanks!

**Comment by pedrobaeza** [comment]
It seems to be incorrect Mailgun parameters.

**Comment by collex100** [comment]
> It seems to be incorrect Mailgun parameters.

I tried everything. There are only three parameters to enter. It's difficult to mix something up. Webhooks works fine. But Re-sync Mailgun  produces the same error. Just three parameters, what could be wrong?

Help me please.
