### ISSUE TITLE
[8.0] Global name 'mail_id' is not defined

### ISSUE THREAD

**Issue by CarlesAntoli** [OCA/social#35]
Module "mass mailing Extra statistic"
When sending a mail displays the following error in the log:

"Traceback (most recent call last):
  File "/opt/odoo/openerp/http.py", line 537, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/openerp/http.py", line 574, in dispatch
    result = self._call_function(*_self.params)
  File "/opt/odoo/openerp/http.py", line 310, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/opt/odoo/openerp/service/model.py", line 118, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/opt/odoo/openerp/http.py", line 307, in checked_call
    return self.endpoint(_a, *_kw)
  File "/opt/odoo/openerp/http.py", line 803, in __call__
    return self.method(_args, *_kw)
  File "/opt/odoo/openerp/http.py", line 403, in response_wrap
    response = f(_args, *_kw)
  File "/opt/odoo/addons/web/controllers/main.py", line 944, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/opt/odoo/openerp/api.py", line 256, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/addons/mail/mail_thread.py", line 1721, in message_post
    msg_id = mail_message.create(cr, uid, values, context=context)
  File "/opt/odoo/openerp/api.py", line 256, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/addons/mail/mail_message.py", line 811, in create
    user_signature=context.get('mail_notify_user_signature', True))
  File "/opt/odoo/openerp/api.py", line 256, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/addons/mail/mail_message.py", line 880, in _notify
    force_send=force_send, user_signature=user_signature
  File "/opt/odoo/openerp/api.py", line 256, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/addons/mail/mail_followers.py", line 261, in _notify
    self._notify_email(cr, SUPERUSER_ID, new_notif_ids, message_id, force_send, user_signature, context=context)
  File "/opt/odoo/openerp/api.py", line 256, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/addons/mail/mail_followers.py", line 227, in _notify_email
    email_ids.append(self.pool.get('mail.mail').create(cr, uid, mail_values, context=context))
  File "/opt/odoo/openerp/api.py", line 256, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/openerp/api.py", line 360, in old_api
    result = method(recs, _args, *_kwargs)
  File "/opt/Extra_Addons/social/mass_mailing_statistic_extra/models/mail_mail.py", line 33, in create
    return mail_id
NameError: global name 'mail_id' is not defined "

¿you know the problem that I can have?
thanks

Carles Antolí

**Comment by hbrunn** [comment]
fixed by #36
