### ISSUE TITLE
error when sending mail without followers as recipients

### ISSUE THREAD

**Issue by enclustra-odoo** [OCA/social#480]
module: mail_optional_follower_notification
version: 12.0

**Steps to reproduce**
- Send e-mail from purchase or sales with the mail composer
- Mail template is `mail.mail_notification_paynow`

**Current behavior**
- e-mail is not sent and the following error is displayed:
```
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/mnt/c/Users/tbrauchli/odoo/odoo-ce/odoo/addons/base/models/qweb.py", line 347, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_330_728
  File "/mnt/c/Users/tbrauchli/odoo/odoo-ce/odoo/models.py", line 1530, in get_access_action
    return self[0].get_formview_action(access_uid=access_uid)
  File "/mnt/c/Users/tbrauchli/odoo/odoo-ce/odoo/models.py", line 5127, in __getitem__
    return self._browse((self._ids[key],), self.env)
IndexError: tuple index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/c/Users/tbrauchli/odoo/odoo-ce/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/mnt/c/Users/tbrauchli/odoo/odoo-ce/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/mnt/c/Users/tbrauchli/odoo/odoo-ce/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/mnt/c/Users/tbrauchli/odoo/odoo-ce/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/mnt/c/Users/tbrauchli/odoo/odoo-ce/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/mnt/c/Users/tbrauchli/odoo/odoo-ce/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/mnt/c/Users/tbrauchli/odoo/odoo-ce/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/mnt/c/Users/tbrauchli/odoo/odoo-ce/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/mnt/c/Users/tbrauchli/odoo/odoo-ce/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/mnt/c/Users/tbrauchli/odoo/odoo-ce/addons/web/controllers/main.py", line 966, in call_button
    action = self._call_kw(model, method, args, {})
  File "/mnt/c/Users/tbrauchli/odoo/odoo-ce/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/mnt/c/Users/tbrauchli/odoo/odoo-ce/odoo/api.py", line 759, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/mnt/c/Users/tbrauchli/odoo/odoo-ce/odoo/api.py", line 746, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/mnt/c/Users/tbrauchli/odoo/odoo-ce/addons/mail/wizard/mail_compose_message.py", line 193, in action_send_mail
    self.send_mail()
  File "/mnt/c/Users/tbrauchli/odoo/odoo-enclustra/mail_optional_follower_notification/wizard/mail_compose_message.py", line 19, in send_mail
    auto_commit=auto_commit)
  File "/mnt/c/Users/tbrauchli/odoo/odoo-ce/addons/mail/wizard/mail_compose_message.py", line 267, in send_mail
    ActiveModel.browse(res_id).message_post(**post_params)
  File "/mnt/c/Users/tbrauchli/odoo/odoo-ce/addons/sale/models/sale.py", line 691, in message_post
    return super(SaleOrder, self.with_context(mail_post_autofollow=True)).message_post(**kwargs)
  File "/mnt/c/Users/tbrauchli/odoo/odoo-ce/addons/rating/models/mail_thread.py", line 14, in message_post
    message = super(MailThread, self).message_post(**kwargs)
  File "/mnt/c/Users/tbrauchli/odoo/odoo-ce/addons/mail/models/mail_thread.py", line 2071, in message_post
    self._message_post_after_hook(new_message, values, model_description=model_description, mail_auto_delete=mail_auto_delete)
  File "/mnt/c/Users/tbrauchli/odoo/odoo-ce/addons/mail_bot/models/mail_thread.py", line 12, in _message_post_after_hook
    return super(MailThread, self)._message_post_after_hook(message, values, model_description=model_description, mail_auto_delete=mail_auto_delete)
  File "/mnt/c/Users/tbrauchli/odoo/odoo-ce/addons/mail/models/mail_thread.py", line 2093, in _message_post_after_hook
    mail_auto_delete=mail_auto_delete,
  File "/mnt/c/Users/tbrauchli/odoo/odoo-enclustra/mail_optional_follower_notification/models/mail_message.py", line 27, in _notify
    mail_auto_delete=mail_auto_delete)
  File "/mnt/c/Users/tbrauchli/odoo/odoo-ce/addons/mail/models/mail_message.py", line 1070, in _notify
    model_description=model_description, mail_auto_delete=mail_auto_delete)
  File "/mnt/c/Users/tbrauchli/odoo/odoo-ee/ocn_client/models/mail_message.py", line 20, in _notify_recipients
    super(MailMessage, self)._notify_recipients(rdata, record, msg_vals, **kwargs)
  File "/mnt/c/Users/tbrauchli/odoo/odoo-ce/addons/mail/models/mail_message.py", line 1150, in _notify_recipients
    self.env['res.partner']._notify(self, partner_email_rdata, record, force_send=force_send, send_after_commit=send_after_commit, model_description=model_description, mail_auto_delete=mail_auto_delete)
  File "/mnt/c/Users/tbrauchli/odoo/odoo-enclustra/mail_optional_follower_notification/models/res_partner.py", line 22, in _notify
    mail_auto_delete=mail_auto_delete)
  File "/mnt/c/Users/tbrauchli/odoo/odoo-ce/addons/mail/models/res_partner.py", line 135, in _notify
    mail_body = base_template.render(template_ctx, engine='ir.qweb', minimal_qcontext=True)
  File "/mnt/c/Users/tbrauchli/odoo/odoo-ce/addons/web_editor/models/ir_ui_view.py", line 29, in render
    return super(IrUiView, self).render(values=values, engine=engine, minimal_qcontext=minimal_qcontext)
  File "/mnt/c/Users/tbrauchli/odoo/odoo-ce/odoo/addons/base/models/ir_ui_view.py", line 1313, in render
    return self.env[engine].render(self.id, qcontext)
  File "/mnt/c/Users/tbrauchli/odoo/odoo-ce/odoo/addons/base/models/ir_qweb.py", line 59, in render
    result = super(IrQWeb, self).render(id_or_xml_id, values=values, **context)
  File "/mnt/c/Users/tbrauchli/odoo/odoo-ce/odoo/addons/base/models/qweb.py", line 275, in render
    self.compile(template, options)(self, body.append, values or {})
  File "/mnt/c/Users/tbrauchli/odoo/odoo-ce/odoo/addons/base/models/qweb.py", line 354, in _compiled_fn
    raise QWebException("Error to render compiling AST", e, path, node and etree.tostring(node[0], encoding='unicode'), name)
odoo.addons.base.models.qweb.QWebException: tuple index out of range
Traceback (most recent call last):
  File "/mnt/c/Users/tbrauchli/odoo/odoo-ce/odoo/addons/base/models/qweb.py", line 347, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_330_728
  File "/mnt/c/Users/tbrauchli/odoo/odoo-ce/odoo/models.py", line 1530, in get_access_action
    return self[0].get_formview_action(access_uid=access_uid)
  File "/mnt/c/Users/tbrauchli/odoo/odoo-ce/odoo/models.py", line 5127, in __getitem__
    return self._browse((self._ids[key],), self.env)
IndexError: tuple index out of range

Error to render compiling AST
IndexError: tuple index out of range
Template: 330
Path: /templates/t/table/tr/td/table/tbody/tr[1]/td/t[1]
Node: <t t-set="access_action" t-value="record.with_context(force_website=True).get_access_action()"/>
```

**Expected behavior**
- e-mail sent only to recipients (without followers)

**Comment by lmignon** [comment]
@enclustra-odoo IMO the problem is into the template. The error occurs since `record` is an empty recordset into `<t t-set="access_action" t-value="record.with_context(force_website=True).get_access_action()"/>`. You should probably enclose this call into a `<t t-if="record"> ... </t>`  tag.

**Comment by theangryangel** [comment]
I'd be extremely happy to be corrected (it's the end of a long day for me, and I've spent far longer than I would like to admit on this), but I think this is an incomplete port from 10.0 to 12.0, as it doesn't seem to take into account the changes between 10 and 12

For example, [the current implementation of _notify method for res.partner](https://github.com/OCA/social/blob/431d57a6f6f297ee180de9729128a924376b2aa8/mail_optional_follower_notification/models/res_partner.py#L17) seems to assume self is a record set, [but in 12.0 that seems not to be the case](https://github.com/odoo/odoo/blob/12.0/addons/mail/models/res_partner.py#L88-L103) as it's annotated api.model and a recordset seems to be passed via one of the args to the function ([10.0](https://github.com/odoo/odoo/blob/10.0/addons/mail/models/mail_message.py#L838), [12.0](https://github.com/odoo/odoo/blob/12.0/addons/mail/models/mail_message.py#L1150))

I'll be digging in again ~~tomorrow~~ shortly. Hopefully with a PR :/

**Comment by georginaf** [comment]
@theangryangel I have the same error when trying to send templates..
If you come up with a PR I'd be happy to test it, just let me know.

**Comment by remihb** [comment]
I'm on it too since 2 days. As far as I can see, this module doesn't seem to work for invoice mails (I don't test all the mail sending for other objects).

It overrides the field 'needaction_partner_ids' in mail.message object but too late because the recipient_data are already calculated (its the rdata parameter in the _notify method).

I'm close to fix the issue, I will make a PR soon ;)

**Comment by remihb** [comment]
Ok done
see that PR [https://github.com/OCA/social/pull/493](https://github.com/OCA/social/pull/493) and let me know if it looks good for you.

**Comment by theangryangel** [comment]
@remihb LGTM and works perfectly as far as I can tell. Was due to start looking at this Friday, so thank you for this <3

Also the invoicing feature is actually what I was ultimately needing, so this is extremely helpful to me!

**Comment by remihb** [comment]
Thx, I added some modifications today to make it work properly, don't hesitate to pull again the branch, waiting for the PR to be merged.

**Comment by gralet** [comment]
Hello, any chance we can merge the PR ?

**Comment by len-foss** [comment]
It should definitely be mergeable, but not in its current state due to the dependency issue. Once fixed I think it should be greenlit.
