### ISSUE TITLE
Mail_tracking error: field not exists

### ISSUE THREAD

**Issue by batona** [OCA/social#485]
This error reproduced on 2 instances. After module install and opening any page related to mail object raised this error.

Ошибка:
Odoo Server Error

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 654, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 312, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 696, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 344, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 337, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 939, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 517, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 962, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 749, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 736, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 2765, in read
    self._read_from_database(stored, inherited)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 2926, in _read_from_database
    field.read(fetched)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 2417, in read
    lines = comodel.search(domain, limit=self.limit)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 1561, in search
    res = self._search(args, offset=offset, limit=limit, order=order, count=count)
  File "/usr/lib/python3/dist-packages/odoo/addons/website_mail/models/mail_message.py", line 46, in _search
    count=count, access_rights_uid=access_rights_uid)
  File "/usr/lib/python3/dist-packages/odoo/addons/calendar/models/mail_message.py", line 25, in _search
    return super(Message, self)._search(args, offset=offset, limit=limit, order=order, count=count, access_rights_uid=access_rights_uid)
  File "/usr/lib/python3/dist-packages/odoo/addons/mail/models/mail_message.py", line 623, in _search
    count=False, access_rights_uid=access_rights_uid)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 4096, in _search
    self._cr.execute(query_str, where_clause_params)
  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 148, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 225, in execute
    res = self._obj.execute(query, params)
psycopg2.ProgrammingError: column mail_message.mail_tracking_needs_action does not exist
LINE 1: ...((("mail_message"."model" = 'res.partner')  AND  ("mail_mess...
                                                             ^

**Comment by pedrobaeza** [comment]
Sorry, this is not a module error, but incorrect deployment of the update. Restart your Odoo service and update the module via command line or UI.

**Comment by batona** [comment]
Sure i did it. I'll try it on brand new installation.

вс, 12 янв. 2020 г., 13:12 Pedro M. Baeza <notifications@github.com>:
