### ISSUE TITLE
[13] mail_tracking ISSUE when uninstalling this addon

### ISSUE THREAD

**Issue by sergioeix** [OCA/social#611]
Odoo 13 Community, Ubuntu 18.04
I am trying to uninstall this addon but i am getting this traceback:
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo13/odoo/odoo/http.py", line 624, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo13/odoo/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo13/odoo/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/opt/odoo13/odoo/odoo/http.py", line 669, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo13/odoo/odoo/http.py", line 350, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo13/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo13/odoo/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo13/odoo/odoo/http.py", line 915, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo13/odoo/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo13/odoo-custom-addons/mail_tracking/controllers/main.py", line 106, in mail_init_messaging
    {"failed_counter": http.request.env["mail.message"].get_failed_count()}
AttributeError: 'mail.message' object has no attribute 'get_failed_count'

After uninstall conversation module stop working and odoo instance becomes unusable.

**Comment by pedrobaeza** [comment]
Just restart your service.

**Comment by pedrobaeza** [comment]
If still not working, then update `mail` module.
