### ISSUE TITLE
[14.0] mail_debrand: TypeError: cannot use a string pattern on a bytes-like object

### ISSUE THREAD

**Issue by ghost** [OCA/social#702]
This error occurs in the app email marketing(mass_mailing) by clicking on "Test" in the Mailings tab

 File "/opt/odoo/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/opt/odoo/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo/http.py", line 359, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo/http.py", line 347, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo/http.py", line 912, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo/http.py", line 531, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo/addons/web/controllers/main.py", line 1368, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/odoo/addons/web/controllers/main.py", line 1356, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo/api.py", line 396, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/odoo/api.py", line 383, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/odoo/addons/mass_mailing/wizard/mailing_mailing_test.py", line 54, in send_mail_test
    mail = self.env['mail.mail'].sudo().create(mail_values)
  File "<decorator-gen-210>", line 2, in create
  File "/opt/odoo/odoo/api.py", line 344, in _model_create_multi
    return create(self, [arg])
  File "/opt/odoo/odoo/addons/mass_mailing/models/mail_mail.py", line 21, in create
    mails = super(MailMail, self).create(values_list)
  File "<decorator-gen-155>", line 2, in create
  File "/opt/odoo/odoo/api.py", line 345, in _model_create_multi
    return create(self, arg)
  File "/opt/odoo/custom-addons/mail_debrand/models/mail_render_mixinANDmail_mail.py", line 98, in create
    values_list[index]["body_html"] = self.env[
  File "/opt/odoo/custom-addons/mail_debrand/models/mail_render_mixinANDmail_mail.py", line 18, in remove_href_odoo
    has_odoo_link = re.search(r"<a\s(.*)odoo\.com", value, flags=re.IGNORECASE)
  File "/usr/lib/python3.8/re.py", line 201, in search
    return _compile(pattern, flags).search(string)
Exception
 
The above exception was the direct cause of the following exception:
 
Traceback (most recent call last):
  File "/opt/odoo/odoo/http.py", line 639, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo/http.py", line 315, in _handle_exception
    raise exception.with_traceback(None) from new_cause
TypeError: cannot use a string pattern on a bytes-like object

**Comment by dhx** [comment]
We also see this problem when odoo tries to process **incoming** mails:
```
INFO ... odoo.addons.fetchmail.models.fetchmail: Failed to process mail from pop server <redacted>. 
Traceback (most recent call last):
  File "/opt/odoo/addons/fetchmail/models/fetchmail.py", line 204, in fetch_mail
    res_id = MailThread.with_context(**additionnal_context).message_process(server.object_id.model, message, save_original=server.original, strip_attachments=(not server.attach))
  File "/opt/odoo/addons/mail/models/mail_thread.py", line 1136, in message_process
    routes = self.message_route(message, msg_dict, model, thread_id, custom_values)
  File "/opt/odoo/addons/mail/models/mail_thread.py", line 993, in message_route
    route = self._routing_check_route(message, message_dict, route, raise_exception=True)
  File "/opt/odoo/addons/mail/models/mail_thread.py", line 832, in _routing_check_route
    self._routing_create_bounce_email(email_from, body, message, references=message_id)
  File "/opt/odoo/addons/mail/models/mail_thread.py", line 685, in _routing_create_bounce_email
    self.env['mail.mail'].sudo().create(bounce_mail_values).send()
  File "<decorator-gen-150>", line 2, in create
  File "/opt/odoo/odoo/api.py", line 344, in _model_create_multi
    return create(self, [arg])
  File "/opt/odoo/addons-oca/mail_debrand/models/mail_render_mixinANDmail_mail.py", line 98, in create
    values_list[index]["body_html"] = self.env[
  File "/opt/odoo/addons-oca/mail_debrand/models/mail_render_mixinANDmail_mail.py", line 18, in remove_href_odoo
    has_odoo_link = re.search(r"<a\s(.*)odoo\.com", value, flags=re.IGNORECASE)
  File "/usr/lib/python3.8/re.py", line 201, in search
    return _compile(pattern, flags).search(string)
TypeError: cannot use a string pattern on a bytes-like object
```
