### ISSUE TITLE
[12.0] mail_drop_target: error in extract_msg external library

### ISSUE THREAD

**Issue by MiquelRForgeFlow** [OCA/social#851]
## Module
`mail_drop_target`

## Describe the bug
SyntaxError in `extract_msg` external library

## To Reproduce
Install `extract_msg` external library:
```
odoo.exceptions.UserError: ('Unable to install module "mail_drop_target" because an external dependency is not met: invalid syntax', '')

Failed to initialize database `openerp_test`.

Traceback (most recent call last):

  File "/home/travis/odoo-12.0/odoo/addons/base/models/ir_module.py", line 337, in check_external_dependencies

    cls._check_external_dependencies(terp)

  File "/home/travis/odoo-12.0/odoo/addons/base/models/ir_module.py", line 323, in _check_external_dependencies

    importlib.import_module(pydep)

  File "/opt/python/3.5.10/lib/python3.5/importlib/__init__.py", line 126, in import_module

    return _bootstrap._gcd_import(name[level:], package, level)

  File "<frozen importlib._bootstrap>", line 985, in _gcd_import

  File "<frozen importlib._bootstrap>", line 968, in _find_and_load

  File "<frozen importlib._bootstrap>", line 957, in _find_and_load_unlocked

  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked

  File "<frozen importlib._bootstrap_external>", line 697, in exec_module

  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed

  File "/home/travis/virtualenv/python3.5.10/lib/python3.5/site-packages/extract_msg/__init__.py", line 36, in <module>

    from .appointment import Appointment

  File "/home/travis/virtualenv/python3.5.10/lib/python3.5/site-packages/extract_msg/appointment.py", line 2, in <module>

    from .attachment import Attachment

  File "/home/travis/virtualenv/python3.5.10/lib/python3.5/site-packages/extract_msg/attachment.py", line 165

    testName = customPath / f'{name} ({i}){ext}'

                                               ^

SyntaxError: invalid syntax
```

**Comment by rafaelbn** [comment]
Dear @MiquelRForgeFlow could you please make the PR to solve it? It's just upstream this one https://github.com/OCA/social/pull/583 from @hbrunn . Maybe @etobella want to review it as he migrate to v12 😄 Thank you!!!!! all of you! ❤️

**Comment by MiquelRForgeFlow** [comment]
Dear @rafaelbn That PR was done in https://github.com/OCA/social/pull/559. That's not the error. The error we are facing is when installing an external library, nothing to do with that module per se.

**Comment by hbrunn** [comment]
this looks very much like the library needs a pin for that python version
