### ISSUE TITLE
[14][XML-RPC] odoo-addon-base-search-mail-content » message_content

### ISSUE THREAD

**Issue by s0me0ther** [OCA/social#902]
## Module
odoo-addon-base-search-mail-content

## Describe the bug
Particular requests via XML-RPC (searchAndRead) on Partner Table will fail with error on «message_content»

## To Reproduce
Activate Base Search Mail Content App

1. request id 1 on table partner via XML-RPC api (searchAndRead)

**Expected behavior**
Successfully fetch row

**Error**
```
Uncaught Odoo\Api\Exception\OdooException: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 793, in get
    return field_cache[record._ids[0]]
KeyError: 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 972, in __get__
    value = env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 796, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: 'res.partner(1,).message_content'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 793, in get
    return field_cache[record._ids[0]]
KeyError: 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1025, in __get__
    value = env.cache.get(re in {private path..}

Fatal error: Uncaught Odoo\Api\Exception\OdooException: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 793, in get
    return field_cache[record._ids[0]]
KeyError: 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 972, in __get__
    value = env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 796, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: 'res.partner(1,).message_content'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 793, in get
    return field_cache[record._ids[0]]
KeyError: 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1025, in {private path..}

Odoo\Api\Exception\OdooException: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 793, in get
    return field_cache[record._ids[0]]
KeyError: 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 972, in __get__
    value = env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 796, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: 'res.partner(1,).message_content'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 793, in get
    return field_cache[record._ids[0]]
KeyError: 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1025, in __get__
    value = env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 796, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: 'res.partner(1,).message_content'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/controllers/rpc.py", line 88, in xmlrpc_2
    response = self._xmlrpc(service)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/controllers/rpc.py", line 68, in _xmlrpc
    result = dispatch_rpc(service, method, params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 142, in dispatch_rpc
    result = dispatch(method, params)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 41, in dispatch
    res = fn(db, uid, *params)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 168, in execute_kw
    return execute(db, uid, obj, method, *args, **kw or {})
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 175, in execute
    res = execute_cr(cr, uid, obj, method, *args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 159, in execute_cr
    result = odoo.api.call_kw(recs, method, args, kw)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 395, in call_kw
    result = _call_kw_model(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 368, in _call_kw_model
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 4859, in search_read
    result = records.read(fields)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3022, in read
    return self._read_format(fnames=fields, load=load)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3042, in _read_format
    vals[name] = convert(record[name], record, use_name_get)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 5686, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1028, in __get__
    raise ValueError("Compute method failed to assign %s.%s" % (record, self.name))
ValueError: Compute method failed to assign res.partner(1,).message_content
 in {private path..}
```

**Comment by bakibakis** [comment]
the same error also when requesting stock.production.lot
```
web_1  | 2022-07-08 08:50:27,256 1 ERROR FORECAST odoo.http: Compute method failed to assign stock.production.lot(10525,).message_content 
web_1  | Traceback (most recent call last):
web_1  |   File "/usr/lib/python3/dist-packages/odoo/api.py", line 793, in get
web_1  |     return field_cache[record._ids[0]]
web_1  | KeyError: 10525
web_1  | 
web_1  | During handling of the above exception, another exception occurred:
web_1  | 
web_1  | Traceback (most recent call last):
web_1  |   File "/usr/lib/python3/dist-packages/odoo/fields.py", line 972, in __get__
web_1  |     value = env.cache.get(record, self)
web_1  |   File "/usr/lib/python3/dist-packages/odoo/api.py", line 796, in get
web_1  |     raise CacheMiss(record, field)
web_1  | odoo.exceptions.CacheMiss: 'stock.production.lot(10525,).message_content'
web_1  | 
web_1  | During handling of the above exception, another exception occurred:
web_1  | 
web_1  | Traceback (most recent call last):
web_1  |   File "/usr/lib/python3/dist-packages/odoo/api.py", line 793, in get
web_1  |     return field_cache[record._ids[0]]
web_1  | KeyError: 10525
web_1  | 
web_1  | During handling of the above exception, another exception occurred:
web_1  | 
web_1  | Traceback (most recent call last):
web_1  |   File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1025, in __get__
web_1  |     value = env.cache.get(record, self)
web_1  |   File "/usr/lib/python3/dist-packages/odoo/api.py", line 796, in get
web_1  |     raise CacheMiss(record, field)
web_1  | odoo.exceptions.CacheMiss: 'stock.production.lot(10525,).message_content'
web_1  | 
web_1  | During handling of the above exception, another exception occurred:
web_1  | 
web_1  | Traceback (most recent call last):
web_1  |   File "/usr/lib/python3/dist-packages/odoo/http.py", line 142, in dispatch_rpc
web_1  |     result = dispatch(method, params)
web_1  |   File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 41, in dispatch
web_1  |     res = fn(db, uid, *params)
web_1  |   File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 168, in execute_kw
web_1  |     return execute(db, uid, obj, method, *args, **kw or {})
web_1  |   File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 94, in wrapper
web_1  |     return f(dbname, *args, **kwargs)
web_1  |   File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 175, in execute
web_1  |     res = execute_cr(cr, uid, obj, method, *args, **kw)
web_1  |   File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 159, in execute_cr
web_1  |     result = odoo.api.call_kw(recs, method, args, kw)
web_1  |   File "/usr/lib/python3/dist-packages/odoo/api.py", line 399, in call_kw
web_1  |     result = _call_kw_multi(method, model, args, kwargs)
web_1  |   File "/usr/lib/python3/dist-packages/odoo/api.py", line 386, in _call_kw_multi
web_1  |     result = method(recs, *args, **kwargs)
web_1  |   File "/usr/lib/python3/dist-packages/odoo/models.py", line 3022, in read
web_1  |     return self._read_format(fnames=fields, load=load)
web_1  |   File "/usr/lib/python3/dist-packages/odoo/models.py", line 3042, in _read_format
web_1  |     vals[name] = convert(record[name], record, use_name_get)
web_1  |   File "/usr/lib/python3/dist-packages/odoo/models.py", line 5686, in __getitem__
web_1  |     return self._fields[key].__get__(self, type(self))
web_1  |   File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1028, in __get__
web_1  |     raise ValueError("Compute method failed to assign %s.%s" % (record, self.name))
web_1  | ValueError: Compute method failed to assign stock.production.lot(10525,).message_content

```

**Comment by bakibakis** [comment]
OK, I have found a workaround.....looks like when you specify the fields which you want to get in XML-RPC read request this issue disappears....

...this worked for me.
