### ISSUE TITLE
[15.0] mail_debrand unexpected keyword argument 'options'

### ISSUE THREAD

**Issue by odaybari** [OCA/social#913]
## Module
mail_debrand

## Describe the bug
After install, sending emails from sales or user invites (tested so far) give me `_render_template() got an unexpected keyword argument 'options'
`
## To Reproduce
**Affected versions**: 15.0

Full error

> RPC_ERROR
Odoo Server Error
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 688, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 360, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 349, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 917, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 536, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1348, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1340, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 464, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 451, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 6472, in onchange
    record._onchange_eval(name, field_onchange[name], result)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 6205, in _onchange_eval
    method_res = method(self)
  File "/usr/lib/python3/dist-packages/odoo/addons/mail/wizard/mail_compose_message.py", line 170, in _onchange_template_id_wrapper
    values = self._onchange_template_id(self.template_id.id, self.composition_mode, self.model, self.res_id)['value']
  File "/usr/lib/python3/dist-packages/odoo/addons/mail/wizard/mail_compose_message.py", line 547, in _onchange_template_id
    values = self.generate_email_for_composer(
  File "/usr/lib/python3/dist-packages/odoo/addons/mail/wizard/mail_compose_message.py", line 658, in generate_email_for_composer
    template_values = self.env['mail.template'].with_context(tpl_partners_only=True).browse(template_id).generate_email(res_ids, fields)
  File "/usr/lib/python3/dist-packages/odoo/addons/account_edi/models/mail_template.py", line 21, in generate_email
    res = super().generate_email(res_ids, fields)
  File "/usr/lib/python3/dist-packages/odoo/addons/mail/models/mail_template.py", line 193, in generate_email
    generated_field_values = template._render_field(
  File "/usr/lib/python3/dist-packages/odoo/addons/mail/models/mail_render_mixin.py", line 550, in _render_field
    return dict(
  File "/usr/lib/python3/dist-packages/odoo/addons/mail/models/mail_render_mixin.py", line 553, in <genexpr>
    for res_id, rendered in template._render_template(
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 644, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 302, in _handle_exception
    raise exception.with_traceback(None) from new_cause
TypeError: _render_template() got an unexpected keyword argument 'options'

>

**Comment by odaybari** [comment]
Hi,

This has been solved by reloading odoo service / docker in my instance.
Hope this helps
