### ISSUE TITLE
[15.0] mail_debrand: portal invite breaks on *.odoo.com domains

### ISSUE THREAD

**Issue by Yenthe666** [OCA/social#940]
## Module
The name of the module that has a bug.
`mail_debrand`

## To Reproduce
**Affected versions**: I presume V13-V15 but confirmed & tested in V15.

1. Setup a new Odoo.sh project that maps to some URL which ends in `.odoo.com` (default behaviour
2. Deploy the `mail_debrand` app on this Odoo.sh project
3. Go to Contacts, open a contact and click on "Action" > "Grant Portal Access" and in the wizard click on "Grant access".
4. You now get an error:
```
  File "/home/odoo/src/odoo/addons/mail/models/mail_render_mixin.py", line 610, in <genexpr>
    for res_id, rendered in template._render_template(
  File "/home/odoo/src/user/mail_debrand/models/mail_render_mixin.py", line 93, in _render_template
    orginal_rendered[key] = self.remove_href_odoo(orginal_rendered[key])
  File "/home/odoo/src/user/mail_debrand/models/mail_render_mixin.py", line 42, in remove_href_odoo
    if remove_parent and len(parent.getparent()):
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/http.py", line 643, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/src/odoo/odoo/http.py", line 301, in _handle_exception
    raise exception.with_traceback(None) from new_cause
TypeError: object of type 'NoneType' has no len()
```

The reason is because the email template `portal.mail_template_data_portal_welcome` (see https://github.com/odoo/odoo/blob/f777abf697adcadcf717976edd88a3b4bae0ad79/addons/portal/data/mail_template_data.xml#L5-L91) has a button "Activate Account" within which builds a signup URL. As this signup URL contains "odoo.com" the `mail_debrand` module picks it up in the `xpath` expression, removes it and destroys the action/mail template.
This problem is very similar to https://github.com/OCA/social/issues/884 but then for another template.

**Expected behavior**
The portal invite email is generated and sent out without breaking over the `xpath`.

**Comment by Yenthe666** [comment]
For those of you looking for a solution.. we built a little extension on top which allows us to add regex options to whitelist options.
`__manifest__.py`:
```
'data': [
        'data/ir_config_parameter.xml'
    ],
```

`data/ir_config_parameter.xml`:
```
<?xml version="1.0" encoding="UTF-8"?>
<odoo>
    <data noupdate="1">
        <record id="mail_debrand_extra_regex" model="ir.config_parameter">
            <field name="key">mail_debrand.extra_regex_to_skip</field>
            <field name="value">False</field>
        </record>
    </data>
</odoo>
```

`models/mail_render_mixin.py` (def remove_href_odoo):
```
    def remove_href_odoo(
        self, value, remove_parent=True, remove_before=False, to_keep=None
    ):
        if len(value) < 20:
            return value
        # value can be bytes type; ensure we get a proper string
        if type(value) is bytes:
            value = value.decode()
        has_odoo_link = re.search(r"<a\s(.*)odoo\.com", value, flags=re.IGNORECASE)
        extra_regex_to_skip = self.env['ir.config_parameter'].sudo().get_param(
            'mail_debrand.extra_regex_to_skip',
            False
        )
        # value is required field on ir config_parameter, so we have added
        # safety check for "False"
        if has_odoo_link and extra_regex_to_skip != "False" and extra_regex_to_skip:
            # check each regex to be skipped
            for regex in extra_regex_to_skip.split(','):
                if re.search(r'{}'.format(regex), value, flags=re.IGNORECASE):
                    has_odoo_link = False
                    break
        if has_odoo_link:
            # We don't want to change what was explicitly added in the message body,
            # so we will only change what is before and after it.
            if to_keep:
                value = value.replace(to_keep, "<body_msg></body_msg>")
            tree = html.fromstring(value)
            odoo_anchors = tree.xpath('//a[contains(@href,"odoo.com")]')
            for elem in odoo_anchors:
                parent = elem.getparent()
                previous = elem.getprevious()
                if remove_before and not remove_parent and previous is not None:
                    # remove 'using' that is before <a and after </span>
                    previous.tail = ""
                if remove_parent and len(parent.getparent()):
                    # anchor <a href odoo has a parent powered by that must be removed
                    parent.getparent().remove(parent)
                else:
                    if parent.tag == "td":  # also here can be powered by
                        parent.getparent().remove(parent)
                    else:
                        parent.remove(elem)
            value = etree.tostring(
                tree, pretty_print=True, method="html", encoding="unicode"
            )
            if to_keep:
                value = value.replace("<body_msg></body_msg>", to_keep)
        return value
```

You can then modify the "mail_debrand_extra_regex" `ir.config_parameter` to hold something like this:
```
<a\s(.*)dev.odoo\.com
```

or
```
<a\s(.*)yourdomain.odoo\.com
```

**Comment by Yenthe666** [comment]
I love how this happens pretty much to any subject where you post lol.
